server:
  address: ":8080"  # 服务器监听地址
  mode: "debug"     # Gin模式: debug, release, test

mongodb:
  uri: "mongodb://localhost:27017/?directConnection=true"  # 使用确认可工作的连接字符串
  database: "minds_iolite"          # 数据库名称
  timeout: 20                        # 增加到20秒
  max_pool_size: 100                # 最大连接池大小

jwt:
  secret: "your-secret-key-here"    # JWT签名密钥
  expiration: 24                    # 令牌过期时间(小时) 